version: "3.4"

services:
  php:
    container_name: php-todo
    build:
      context: .
      args:
        SYMFONY_VERSION: ${SYMFONY_VERSION:-}
        SKELETON: ${SKELETON:-symfony/skeleton}
        STABILITY: ${STABILITY:-stable}
    volumes:
      - .:/var/www/html
    depends_on:
      - database

  database:
    container_name: database-todo
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: symfony_docker
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '5316:3306'
    volumes:
      - ./mysql:/var/lib/mysql

  nginx:
    container_name: nginx-todo
    image: nginx:stable-alpine
    ports:
      - '92:80'
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
